In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('abs-change-energy-consumption.csv')
import re
pd.set_option('display.max_rows', None)
new_data = data.loc[data['Entity'].str.contains('Philippines' , regex=True)]
new_data

,Entity,Code,Year,Annual change in primary energy consumption (TWh)
8947,Philippines,PHL,1966,4.404240
8948,Philippines,PHL,1967,7.291370
8949,Philippines,PHL,1968,8.593918
8950,Philippines,PHL,1969,5.341965
8951,Philippines,PHL,1970,11.088257
8952,Philippines,PHL,1971,13.169312
8953,Philippines,PHL,1972,-1.029388
8954,Philippines,PHL,1973,17.308685
8955,Philippines,PHL,1974,-8.266274
8956,Philippines,PHL,1975,9.293663
8957,Philippines,PHL,1976,4.805817
8958,Philippines,PHL,1977,9.867317
8959,Philippines,PHL,1978,5.950745
8960,Philippines,PHL,1979,6.042877
8961,Philippines,PHL,1980,-2.359116
8962,Philippines,PHL,1981,-0.490540
8963,Philippines,PHL,1982,-4.094818
8964,Philippines,PHL,1983,11.590225
8965,Philippines,PHL,1984,-13.533783
8966,Philippines,PHL,1985,-4.701355
8967,Philippines,PHL,1986,2.113831
8968,Philippines,PHL,1987,11.206314
8969,Philippines,PHL,1988,15.258240
8970,Philippines,PHL,1989,13.367615
8971,Philippines,PHL,1990,10.572708
8972,Philippines,PHL,1991,-2.929169
8973,Philippines,PHL,1992,13.432404
8974,Philippines,PHL,1993,19.229141
8975,Philippines,PHL,1994,9.062820
8976,Philippines,PHL,1995,32.171190
8977,Philippines,PHL,1996,18.473663
8978,Philippines,PHL,1997,25.341340
8979,Philippines,PHL,1998,-1.049255
8980,Philippines,PHL,1999,3.859405
8981,Philippines,PHL,2000,2.383484
8982,Philippines,PHL,2001,-6.825165
8983,Philippines,PHL,2002,1.440826
8984,Philippines,PHL,2003,9.573425
8985,Philippines,PHL,2004,7.380676
8986,Philippines,PHL,2005,1.193665
8987,Philippines,PHL,2006,-15.150391
8988,Philippines,PHL,2007,11.455017
8989,Philippines,PHL,2008,10.754425
8990,Philippines,PHL,2009,3.850006
8991,Philippines,PHL,2010,9.616455
8992,Philippines,PHL,2011,6.805969
8993,Philippines,PHL,2012,11.971008
8994,Philippines,PHL,2013,25.798310
8995,Philippines,PHL,2014,20.162140
8996,Philippines,PHL,2015,38.904970
8997,Philippines,PHL,2016,40.996063
8998,Philippines,PHL,2017,47.133360
8999,Philippines,PHL,2018,14.643494
9000,Philippines,PHL,2019,16.169922
9001,Philippines,PHL,2020,-51.236940
9002,Philippines,PHL,2021,33.517640
9003,Philippines,PHL,2022,39.805237

In [4]:
new_data = new_data.reset_index(drop=True)
new_data.to_csv('abs-change-energy-consumption.csv')

In [5]:
pd.set_option('display.max_rows', None)
new_data = new_data.loc[new_data['Year'] >= 1991]
new_data = new_data.reset_index(drop=True)
new_data

         Entity Code  Year  Annual change in primary energy consumption (TWh)
0   Philippines  PHL  1991                                          -2.929169
1   Philippines  PHL  1992                                          13.432404
2   Philippines  PHL  1993                                          19.229141
3   Philippines  PHL  1994                                           9.062820
4   Philippines  PHL  1995                                          32.171190
5   Philippines  PHL  1996                                          18.473663
6   Philippines  PHL  1997                                          25.341340
7   Philippines  PHL  1998                                          -1.049255
8   Philippines  PHL  1999                                           3.859405
9   Philippines  PHL  2000                                           2.383484
10  Philippines  PHL  2001                                          -6.825165
11  Philippines  PHL  2002                                           1.440826
12  Philippines  PHL  2003                                           9.573425
13  Philippines  PHL  2004                                           7.380676
14  Philippines  PHL  2005                                           1.193665
15  Philippines  PHL  2006                                         -15.150391
16  Philippines  PHL  2007                                          11.455017
17  Philippines  PHL  2008                                          10.754425
18  Philippines  PHL  2009                                           3.850006
19  Philippines  PHL  2010                                           9.616455
20  Philippines  PHL  2011                                           6.805969
21  Philippines  PHL  2012                                          11.971008
22  Philippines  PHL  2013                                          25.798310
23  Philippines  PHL  2014                                          20.162140
24  Philippines  PHL  2015                                          38.904970
25  Philippines  PHL  2016                                          40.996063
26  Philippines  PHL  2017                                          47.133360
27  Philippines  PHL  2018                                          14.643494
28  Philippines  PHL  2019                                          16.169922
29  Philippines  PHL  2020                                         -51.236940
30  Philippines  PHL  2021                                          33.517640
31  Philippines  PHL  2022                                          39.805237

In [6]:
# Calculate the relative change
new_data['Relative_change'] = new_data['Annual change in primary energy consumption (TWh)'].pct_change() * 100

# Calculate the absolute change
new_data['Absolute_change'] = new_data['Annual change in primary energy consumption (TWh)'].diff().abs()

In [7]:
print("Importing data")
import re

df = new_data.loc[new_data['Entity'].str.contains('Philippines', regex=True)]
df = df.rename(columns={'Entity': 'Entity','Year':'Year', 'Annual change in primary energy consumption (TWh)': 'Annual_change(Twh)',
                        'Absolute_change': 'Absolute_change(Twh)', 'Relative_change': 'Relative_change (%)'})
df = df.drop(columns=['Code'])

Importing data

In [8]:
mod_data = pd.merge(new_data,df)
mod_data[['Entity','Year','Annual_change(Twh)','Absolute_change(Twh)', 'Relative_change (%)']]

,Entity,Year,Annual_change(Twh),Absolute_change(Twh),Relative_change (%)
0,Philippines,1991,-2.929169,NaN,NaN
1,Philippines,1992,13.432404,16.361573,-558.573929
2,Philippines,1993,19.229141,5.796737,43.154874
3,Philippines,1994,9.062820,10.166321,-52.869346
4,Philippines,1995,32.171190,23.108370,254.979907
5,Philippines,1996,18.473663,13.697527,-42.576998
6,Philippines,1997,25.341340,6.867677,37.175502
7,Philippines,1998,-1.049255,26.390595,-104.140489
8,Philippines,1999,3.859405,4.908661,-467.823268
9,Philippines,2000,2.383484,1.475921,-38.242198
10,Philippines,2001,-6.825165,9.208649,-386.352457
11,Philippines,2002,1.440826,8.265991,-121.110499
12,Philippines,2003,9.573425,8.132599,564.439866
13,Philippines,2004,7.380676,2.192749,-22.904537
14,Philippines,2005,1.193665,6.187012,-83.827165
15,Philippines,2006,-15.150391,16.344056,-1369.233502
16,Philippines,2007,11.455017,26.605408,-175.608722
17,Philippines,2008,10.754425,0.700592,-6.116028
18,Philippines,2009,3.850006,6.904419,-64.200727
19,Philippines,2010,9.616455,5.766449,149.777663
20,Philippines,2011,6.805969,2.810486,-29.225801
21,Philippines,2012,11.971008,5.165039,75.889840
22,Philippines,2013,25.798310,13.827302,115.506581
23,Philippines,2014,20.162140,5.636170,-21.847051
24,Philippines,2015,38.904970,18.742830,92.960519
25,Philippines,2016,40.996063,2.091093,5.374874
26,Philippines,2017,47.133360,6.137297,14.970455
27,Philippines,2018,14.643494,32.489866,-68.931784
28,Philippines,2019,16.169922,1.526428,10.423933
29,Philippines,2020,-51.236940,67.406862,-416.865721
30,Philippines,2021,33.517640,84.754580,-165.416943
31,Philippines,2022,39.805237,6.287597,18.759068

Elijah P. Dela Cruz

2020103390

Absolute change would refer to the difference over two periods in time, in this case we are comparing the Annual change in primary energy consumption (TWh) of the Philippines from 1992 to 2022. Relative change is the absolute change in percent form. Judging from the data displayed, it could be deemed from 1998 to 2005 and 2007 to 2013 as one of the more consistent when it came to the primary energy consumption. From my source, primary energy would be defined as "commercially-traded fuels, including modern renewables used to generate electricity. Energy from all sources of non-fossil power generation is accounted for on an input-equivalent basis." Which is why in 2020, when there was a worldwide lockdown; the Annual change in primary energy consumption took a sharp dive.